// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DpXxs4zAeF0S2gCh-jKSDRqBHK6xztc',
    appId: '1:1057573798323:web:e419996a89258cb1f5cbc6',
    messagingSenderId: '1057573798323',
    projectId: 'allo-doct',
    authDomain: 'allo-doct.firebaseapp.com',
    storageBucket: 'allo-doct.firebasestorage.app',
    measurementId: 'G-LP8WG42KZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-ou6j9YKPpqYv2Zl2SIsqQdqSciksps',
    appId: '1:1057573798323:android:172dffd3cb6206b8f5cbc6',
    messagingSenderId: '1057573798323',
    projectId: 'allo-doct',
    storageBucket: 'allo-doct.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeP2UAwA4bskOVpPqiogQEFxz-DF0wyOE',
    appId: '1:1057573798323:ios:61975c4017bb1397f5cbc6',
    messagingSenderId: '1057573798323',
    projectId: 'allo-doct',
    storageBucket: 'allo-doct.firebasestorage.app',
    iosBundleId: 'com.allodoct.alloDoct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeP2UAwA4bskOVpPqiogQEFxz-DF0wyOE',
    appId: '1:1057573798323:ios:61975c4017bb1397f5cbc6',
    messagingSenderId: '1057573798323',
    projectId: 'allo-doct',
    storageBucket: 'allo-doct.firebasestorage.app',
    iosBundleId: 'com.allodoct.alloDoct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9DpXxs4zAeF0S2gCh-jKSDRqBHK6xztc',
    appId: '1:1057573798323:web:241d29a079c34027f5cbc6',
    messagingSenderId: '1057573798323',
    projectId: 'allo-doct',
    authDomain: 'allo-doct.firebaseapp.com',
    storageBucket: 'allo-doct.firebasestorage.app',
    measurementId: 'G-GSGK28H5MD',
  );
}
